# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Bellatrix Docs
email: aangelov@bellatrix.solutions
description: >- # this means to ignore newlines until "baseurl:"
  Here you can find rich documentation about the different features and configurations of Bellatrix Test Framework.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://docs.bdd.bellatrix.solutions" # the base hostname & protocol for your site, e.g. http://example.com
#twitter_username: jekyllrb
#github_username:  jekyll
permalink: /:title/
#source: jekyll
#destination: documentation 
# Build settings
markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM
  syntax_highlighter: rouge
# theme: minima
plugins:

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
navigation: 
    "overview":
        title: BDD Overview
        submenu:
    "general-information":
        title: General Information
        submenu:
            "system-requirements":
                title: System Requirements
            "installation-windows":
                title: Installation Windows
            "installation-macos":
                title: Installation MacOS
            "installation-linux":
                title: Installation Linux
            "update":
                title: Update
    "web-automation":
        title: Web
        submenu:
            "control-browser":
                title: Control Browser
            "navigate-to-pages":
                title: Navigate to Pages
            "browser-service":
                title: BrowserService
            "cookies-service":
                title: CookiesService
            "bdd-logging":
                title: BDD Logging
            "troubleshooting-full-page-screenshots-on-fail":
                title: Troubleshooting- Full Page Screenshots on Fail
            "troubleshooting-video-recording":
                title: Troubleshooting- Video Recording
            "capture-http-traffic":
                title: Capture HTTP Traffic
            "execute-tests-selenium-grid":
                title: Execute Tests in Selenium Grid
            "execute-tests-saucelabs":
                title: Execute Tests in SauceLabs
            "execute-tests-browserstack":
                title: Execute Tests in BrowserStack
            "execute-tests-crossbrowsertesting":
                title: Execute Tests in CrossBrowserTesting
            "add-custom-webdriver-capabilities-options":
                title: Add Custom WebDriver Capabilities and Options
            "static-analysis":
                title: Static Analysis
            "measure-test-execution-times": 
                title: Measure Response Times
            "load-testing": 
                title: Web Load Testing
            "extensibility-test-workflow-hooks":
                title: Extensibility- Test Workflow Hooks           
            "templates":
                title: Templates
            "folder-and-file-structure":
                title: Folder and File Structure
    "android-automation":
        title: Android
        submenu:
            "control-app":
                title: Control App
            "navigate-to-activities":
                title: Navigate To Activities
            "app-service":
                title: AppService
            "device-service":
                title: DeviceService
            "file-system-service":
                title: FileSystemService
            "keyboard-service":
                title: KeyboardService
            "bdd-logging":
                title: BDD Logging
            "troubleshooting-screenshots-on-fail":
                title: Troubleshooting- Screenshots on Fail
            "troubleshooting-video-recording":
                title: Troubleshooting- Video Recording
            "execute-tests-saucelabs":
                title: Execute Tests in SauceLabs
            "execute-tests-browserstack":
                title: Execute Tests in BrowserStack
            "execute-tests-crossbrowsertesting":
                title: Execute Tests in CrossBrowserTesting
            "add-custom-appium-options":
                title: Add Custom Appium Capabilities
            "static-analysis":
                title: Static Analysis
            "measure-test-execution-times": 
                title: Measure Response Times
            "extensibility-test-workflow-hooks":
                title: Extensibility- Test Workflow Hooks          
            "templates":
                title: Templates
            "folder-and-file-structure":
                title: Folder and File Structure
    "ios-automation":
        title: iOS
        submenu:
            "control-app":
                title: Control App
            "app-service":
                title: AppService
            "device-service":
                title: DeviceService
            "keyboard-service":
                title: KeyboardService
            "bdd-logging":
                title: BDD Logging
            "troubleshooting-screenshots-on-fail":
                title: Troubleshooting- Screenshots on Fail
            "troubleshooting-video-recording":
                title: Troubleshooting- Video Recording
            "execute-tests-saucelabs":
                title: Execute Tests in SauceLabs
            "execute-tests-browserstack":
                title: Execute Tests in BrowserStack
            "execute-tests-crossbrowsertesting":
                title: Execute Tests in CrossBrowserTesting
            "add-custom-appium-options":
                title: Add Custom Appium Capabilities
            "static-analysis":
                title: Static Analysis
            "measure-test-execution-times": 
                title: Measure Response Times
            "extensibility-test-workflow-hooks":
                title: Extensibility- Test Workflow Hooks         
            "templates":
                title: Templates
            "folder-and-file-structure":
                title: Folder and File Structure
    "desktop-automation":
        title: Desktop
        submenu:
            "control-app":
                title: Control App           
            "app-service":
                title: AppService
            "bdd-logging":
                title: BDD Logging
            "troubleshooting-screenshots-on-fail":
                title: Troubleshooting- Screenshots on Fail
            "troubleshooting-video-recording":
                title: Troubleshooting- Video Recording
            "add-custom-webdriver-capabilities":
                title: Add Custom WebDriver Capabilities
            "static-analysis":
                title: Static Analysis
            "measure-test-execution-times": 
                title: Measure Response Times
            "extensibility-test-workflow-hooks":
                title: Extensibility- Test Workflow Hooks          
            "templates":
                title: Templates
            "folder-and-file-structure":
                title: Folder and File Structure
    "api-automation":
        title: API
        submenu:           
            "bdd-logging":
                title: BDD Logging
            "authentication":
                title: Authentication
            "retry-failed-requests":
                title: Retry Failed Requests
            "static-analysis":
                title: Static Analysis
            "extensibility-test-workflow-hooks":
                title: Extensibility- Test Workflow Hooks         
            "measure-response-times":
                title: Measure Response Times
            "templates":
                title: Templates
            "folder-and-file-structure":
                title: Folder and File Structure